parameters:
#    player.example.class: Screeper\PlayerBundle\Example

services:
    screeper.player.services.player:
        class: Screeper\PlayerBundle\Services\PlayerService
        arguments:
            - '@service_container'
            - '@doctrine.orm.entity_manager'

    screeper.player.services.uuid:
        class: Screeper\PlayerBundle\Services\UUIDService
        arguments:
            - '@service_container'
            - '@doctrine.orm.entity_manager'